spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/lagitech
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: VotreCleSecreteTresLonguePourJWT32Caracteres
  expiration: 86400000