spring:
  datasource:
    url: jdbc:postgresql://192.168.100.27:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: dev_user
    password: dev1234
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true

jwt:
  secret: VotreCleSecreteTresLonguePourJWT32Caracteres
  expiration: 86400000
